config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations', registrations: 'users/registrations' }
  resources :tasks
  resources :projects
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount ActionCable.server => "/cable"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: 'projects#index'

  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index]
    end
  end
end

app/views/layouts/_navbar.html.haml
%nav.bg-gray-800{ data: { controller: "user-menu mobile-menu", action: "click@window->user-menu#closeIfOutside click@window->mobile-menu#closeIfOutside" } }
  %div{ class: "mx-auto max-w-[90%] px-2 sm:px-6 lg:px-8" }
    .relative.flex.h-16.items-center.justify-between
      .absolute.inset-y-0.left-0.flex.items-center.sm:hidden
        %button{ type: "button",
                 class: "relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:ring-2 focus:ring-white focus:outline-hidden focus:ring-inset",
                 aria: { controls: "mobile-menu", expanded: "false" },
                 data: { action: "click->mobile-menu#toggle" } }
          %span.absolute.-inset-0.5
          %span.sr-only Open main menu
          %svg.block.h-6.w-6{ fill: "none", viewBox: "0 0 24 24", "stroke-width": "1.5", stroke: "currentColor", aria: { hidden: "true" } }
            %path{ "stroke-linecap": "round", "stroke-linejoin": "round", d: "M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" }
          %svg.hidden.h-6.w-6{ fill: "none", viewBox: "0 0 24 24", "stroke-width": "1.5", stroke: "currentColor", aria: { hidden: "true" } }
            %path{ "stroke-linecap": "round", "stroke-linejoin": "round", d: "M6 18 18 6M6 6l12 12" }

      .flex.flex-1.items-center.justify-center.sm:items-stretch.sm:justify-start
        .flex.shrink-0.items-center
          = image_tag "https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=500",
                      class: "h-8 w-auto",
                      alt: "Your Company"
        .hidden.sm:ml-6.sm:block
          .flex.space-x-4
            = nav_link_to "Projects", projects_path, block: true
            = nav_link_to "Tasks", tasks_path, block: true
            - if can? :manage, User
              = nav_link_to "Users", users_path, block: true

      .absolute.inset-y-0.right-0.flex.items-center.pr-2.sm:static.sm:inset-auto.sm:ml-6.sm:pr-0
        .relative.ml-3
          %button{ type: "button",
                   id: "user-menu-button",
                   class: "relative flex rounded-full bg-gray-800 text-sm focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 focus:outline-hidden",
                   aria: { expanded: "false", haspopup: "true" },
                   data: { action: "click->user-menu#toggle" } }
            %span.absolute.-inset-1.5
            %span.sr-only Open user menu
            = render "users/user_avatar", user: current_user
          %div{ data: { "user-menu-target": "menu" },
                class: "absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black/5 focus:outline-hidden hidden",
                role: "menu" }
            = link_to "Your Profile", edit_user_registration_path,
                      class: "block px-4 py-2 text-sm text-gray-700",
                      role: "menuitem"
            = link_to "Sign out", destroy_user_session_path,
                      method: :delete,
                      class: "block px-4 py-2 text-sm text-gray-700",
                      role: "menuitem"

  #mobile-menu.sm:hidden.hidden{ data: { "mobile-menu-target": "menu" } }
    .space-y-1.px-2.pt-2.pb-3
      = nav_link_to "Projects", projects_path, block: true, active: true
      = nav_link_to "Tasks", tasks_path, block: true
      - if can? :manage, User
        = nav_link_to "Users", users_path, block: true

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= content_for(:title) || "Gatekeeper"
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    %meta{name: "apple-mobile-web-app-capable", content: "yes"}
    %meta{name: "mobile-web-app-capable", content: "yes"}
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    -# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    -#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json)

    %link{ rel: "icon", href: "/icon.png", type: "image/png" }
    %link{ rel: "icon", href: "/icon.svg", type: "image/svg+xml" }
    %link{ rel: "apple-touch-icon", href: "/icon.png" }

    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags

  %body
    = render "shared/toast_container"
    - if user_signed_in?
      = render "layouts/navbar"
    -#= render "shared/flash"
    %main.container.mx-auto.mt-28.px-5.flex
      = yield